### ISSUE TITLE
`ctrl+click` shortcut to select multiple items in the “Cinnamon on Wayland (Experimental)” does not register or work.

### ISSUE THREAD

**Issue by dazzletune** [linuxmint/wayland#100]
### Distribution

EndeavourOS (rolling)

### Package version

6.2.2

### Graphics hardware in use

AMD Barcelo @ 0.40 GHz [Integrated]

### Frequency

Always

### Bug description

Whenever I try selecting multiple items using the `ctrl+click` keyboard shortcut on the Cinnamon Wayland session, such as when using `timeshift-gtk`, the keyboard shortcut command to select multiple items doesn't register and one item is selected when multiple should be selected.

### Steps to reproduce

1. Run the “Cinnamon on Wayland (Experimental)” session from a login display manager.
2. Open an application that supports `ctrl+click` functionality.
3. Attempt to use `ctrl+click` with the intent of selecting multiple items.
4. Issue is encountered. 

### Expected behavior

Multiple items should be able to be selected, using `ctrl+click`.

**Comment by JosephMcc** [comment]
A basic search would show this issue has already been reported multiple times: https://github.com/linuxmint/wayland/issues/1
