### ISSUE TITLE
Cinnamon Wayland - Desktop appear within programs causing instability.

### ISSUE THREAD

**Issue by the-aristocat** [linuxmint/wayland#102]
### Distribution

LMDE 6

### Package version

6.2.7

### Graphics hardware in use

AMD Radeon RX 6600

### Frequency

Always

### Bug description

In a Cinnamon Wayland session, the Desktop will appear as a program at the bottom. Opening other programs will sometimes allow the Desktop to show itself within another program, exposing icons within it and freezing up the workstation all together. "Closing" the desktop results in nothing. Restarting does not resolve the issue.

### Steps to reproduce

1. Open up Cinnamon under Wayland session.
2. Click the "gear" icon representing the Desktop, especially within another program.
3. Desktop icons & will appear within the program.

### Expected behavior

Desktop should not appear as a program at the bottom panel.

**Comment by the-aristocat** [comment]
An example of the behavior in question impacting VLC media player. Desktop icons will show up within the program.
![desktop](https://github.com/user-attachments/assets/272e2ee8-06fc-434a-a277-1a7b474d67dc)

**Comment by haggen88** [comment]
I confirm the bug, also appears in hot corners:

![Screenshot from 2024-07-28 14-31-47](https://github.com/user-attachments/assets/d3b1e2a8-6cf5-47d1-b198-5af89822e403)
