### ISSUE TITLE
Wayland - Keys missing: CTRL(both), SHIFT(both), ALT, ALT GR

### ISSUE THREAD

**Issue by liszca** [linuxmint/wayland#108]
### Distribution

Linux Mint 22.0

### Package version

6.2.9

### Graphics hardware in use

Radeon 7900

### Frequency

Always

### Bug description

Problems only occur when using Wayland.

Missing keys mainly in Games, it seems like it doesn't matter if native or Proton. Besides Games FreeCAD has also troubles.

Missing keys are: CTRL(both), SHIFT(both), ALT, ALT GR
Also I noticed the virtual keyboard has the same keys not functioning.

### Steps to reproduce

Start a Proton game and try to use CTRL for example in Satisfactory.

**Select different files using CTRL in Nemo SHIFT also has no meaning.**

### Expected behavior

In Satisfactory do jump.
In Counter-Strike 2 do crouch

### Additional information

Cannot add any keyboard layout tab is missing in Settings.

I can try fixes just let me know what to try - got BTRFS ;)

**Comment by JosephMcc** [comment]
Please use search when opening issues. This has already been reported many times and is known: https://github.com/linuxmint/wayland/issues/1
