### ISSUE TITLE
Blank Screen

### ISSUE THREAD

**Issue by username227** [linuxmint/wayland#111]
### Distribution

Arch

### Package version

6.2.9

### Graphics hardware in use

GeForce GTX 1650 & integrated AMD Radeon

### Frequency

Always

### Bug description

Get a black screen and computer freezes up. Sometimes mouse appears before freeze.

### Steps to reproduce

Start Cinnamon with wayland session.

### Expected behavior

Should start normally.

### Additional information

Wayland has worked in the past. I logged into wayland for the first time in awhile to do something on Waydroid, but my computer consistently froze up. I tried both the linux kernel and linux-lts kernel, both same result. I also tried both Nvidia and integrated graphics cards, same result. I then tried wayland with gnome and it worked fine, leading to the conclusion that it is cinnamon-related.

**Comment by leigh123linux** [comment]
> ### Additional information
> Wayland has worked in the past. I logged into wayland for the first time in awhile to do something on Waydroid, but my computer consistently froze up. I tried both the linux kernel and linux-lts kernel, both same result. I also tried both Nvidia and integrated graphics cards, same result. I then tried wayland with gnome and it worked fine, leading to the conclusion that it is cinnamon-related.


It works fine here on fedora, so I reached a different conclusion, archlinux is busted so report your issue to them instead.

**Comment by username227** [comment]
I'm sorry you don't like Arch but I shouldn't be the one to suffer because of your idiotic biases. Thanks so much.

**Comment by leigh123linux** [comment]
> I'm sorry you don't like Arch but I shouldn't be the one to suffer because of your idiotic biases. Thanks so much.

Get the archlinux maintainer to enable egl_device and to do further testing, his packaging is a mess, maybe he should rebase his pkgbuild on mutter 

He needs to add this to

-Degl_device=true

https://gitlab.archlinux.org/archlinux/packaging/packages/muffin/-/blob/main/PKGBUILD?ref_type=heads#L23
