### ISSUE TITLE
Scandinavian keyboard Wayland problem

### ISSUE THREAD

**Issue by mahtiankka** [linuxmint/wayland#17]
The letters like äää ööö ååå are missing. It would seem that a US keyboard is in use. The problem only occurs on the Wayland side.

In the settings, the Finnish keyboard is selected and the letters on the xorg side work normally.

![scandinavia](https://github.com/linuxmint/mint21.3-beta/assets/48694735/35bd62d5-f1ea-4f41-872d-374721072d6f)

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/wayland/issues/14
