### ISSUE TITLE
Cannot take a screenshot of the desktop using the Prtscn key

### ISSUE THREAD

**Issue by haggen88** [linuxmint/wayland#19]
### Distribution

Mint 21.3

### Package version

gnome-screenshot 41.0

### Frequency

Always

### Bug description

Pressing the prtscn key on the desktop does not display the screenshot menu.

### Steps to reproduce

Press the prtscn key while on the desktop

### Expected behavior

Take a screenshot of the desktop

**Comment by haggen88** [comment]
I don't know if it is related but when taking a screenshot of the windows when hot corners is active, all windows are taken as background.

![w-screenshot fondo](https://github.com/linuxmint/wayland/assets/68134588/641d7b3b-4691-4083-bfd4-31c9464223ea)

**Comment by WhosyVox** [comment]
I've found that invoking `gnome-screenshot` from the terminal (after the printscreen key lockup) will cause two screenshots to occur at once, and then after that the printscreen key will work consistently. 

Edit: Even more interesting, just opening a few more applications of any kind seems to trigger a screenshot to finally take. No terminal output from `gnome-screenshot`. It did, however, prevent gnome-system-monitor from opening until the screenshot had completed.

Once a screenshot has been taken, the application plays nice on cinnamon-wayland until a system reboot. It continues to play nice even after logging out and back in, and even after restarting lightdm.

**Comment by haggen88** [comment]
With Cinnamon 6.2.7 I can use the Prtscn key

**Comment by haggen88** [comment]
With Cinnamon 6.2.7 I can use the Prtscn.  I see no problems launching gnome-screenshot via terminal.
