### ISSUE TITLE
Apps needing superuser password crashing

### ISSUE THREAD

**Issue by BobasoT** [linuxmint/wayland#22]
I'm not sure if I read or heard this may be an issue already but thought I'd file. Apps such as Timeshift, Synaptic and Update Manager were either not loading or crashing when the box for the password was supposed to pop up and didn't. When I noticed it, I reinstalled clean and only applied updates and not setup the system yet. Testing hardware install on a Lenovo Laptop Ideapad 3 with Ryzen 3 CPU and graphics, 12GB RAM. Stock kernel and hwe kernel had same behavior.

With Timeshift, Looking Glass said this:
(cinnamon:9665): Gjs-Console-CRITICAL **: 16:33:16.096: rgba(55, 27, 77, 204)

(cinnamon:9665): Gjs-Console-CRITICAL **: 16:33:16.959: rgba(55, 27, 77, 204)

When I tried to refresh the repos in Update Manager, it failed, reportedit failed and then logged this:
(cinnamon:9665): mutter-CRITICAL **: 16:34:33.037: meta_window_set_stack_position_no_sync: assertion 'window->stack_position >= 0' failed

I can launch all these with a sudo command from the terminal where Synaptic and Timeshift appear to function correctly. No issues in X.

**Comment by haggen88** [comment]
I confirm, mintsources, synaptic, timeshift, users and group, firewall and languages present this problem. No window opens asking for the password.

**Comment by MineShadow7** [comment]
Can confirm the same issue
