### ISSUE TITLE
redshift not working

### ISSUE THREAD

**Issue by haggen88** [linuxmint/wayland#24]
### Distribution

MInt 21.3

### Package version

redshift 1.12

### Frequency

Always

### Bug description

It is not possible to adjust the screen color temperature using redshift in a wayland session.

### Steps to reproduce

Activate redshift-gtk or install applets like  redshift@marvel4u / qredshift@quintao

### Expected behavior

the screen changes color temperature

### Additional information

when running redshift in terminal:

mint@mint:~$ redshift
Trying location provider `geoclue2'...
Using provider `geoclue2'.
Failed to start adjustment method wayland.
Trying next method...
Using method `randr'.
Waiting for initial location to become available...
Location: ##.## S, ##.## W

PS. Maybe LM in the future will be able to use something like [gammastep](https://gitlab.com/chinstrap/gammastep) (works on Ubuntu and Debian, as well as X11 and Wayland).

**Comment by leigh123linux** [comment]
Redshift isn't compatible with wayland.

https://github.com/jonls/redshift/issues/55

**Comment by leifliddy** [comment]
There is a package called `wl-gammactl` 
https://github.com/mischw/wl-gammactl 
that "should" allow you to adjust the gamma levels. 
But, it doesn't look like it's supported by cinnamon yet
Currently receiving this error
```compositor doesn't support wlr-gamma-control-unstable-v1```

**Comment by LinuxOnTheDesktop** [comment]
There is [gammastep](https://gitlab.com/chinstrap/gammastep), which is a drop-in replacement (or pretty much) for redshift and which supports Wayland, and/but which works via wlroots (as the linked page says).

**Comment by Splarkszter** [comment]
Gamma is being discussed but what we want is screen color Temperature control to reduce Eye Strain.

Just like F.Lux for windows does.

> There is [gammastep](https://gitlab.com/chinstrap/gammastep), which is a drop-in replacement (or pretty much) for redshift and which supports Wayland, and/but which works via wlroots (as the linked page says).

I'm getting the error `Failed to start adjustment method: wayland`
And also if i try to use that adjustment method on QRedshift my DE crashes and i have to force turn off my computer.
