### ISSUE TITLE
Refresh in update manager show an error: cannot refresh the update list

### ISSUE THREAD

**Issue by marmotte32** [linuxmint/wayland#26]
### Distribution

Mint 21.3

### Package version

6.0.1

### Graphics hardware in use

Intel HD Graphics 4400 (HSW GT2) v: 4.6 Mesa 23.0.4-0ubuntu1~22.04.1

### Frequency

Always

### Bug description

Clicking on Refresh button in update manager show this error: cannot refresh the update list

### Steps to reproduce

Start the update manager
If packages are up to date it will show as usual: Your system is up to date
But if you click on Refresh button this error will be shown: cannot refresh the update list
![error](https://github.com/linuxmint/wayland/assets/4152464/feb810e2-a492-4b25-8dbc-d352ec741ede)

### Expected behavior

the status shown should be:  Your system is up to date

### Additional information

in place upgrade done from Mint Cinnamon 21.2 to 21.3 today

**Comment by PiperKev** [comment]
In addition, Software Sources will not load.  Just tested on the released version of 21.3 today.

**Comment by rcalixte** [comment]
This is probably related to `pkexec` not working in the Wayland session yet. This also impacts tons of modules in the settings as well.

**Comment by mtwebster** [comment]
A wip here for the polkit fix to allow things like mintsources, etc.. to work once more:
https://github.com/mtwebster/Cinnamon/commit/461242e33b7bec79749de6583095b7e9c031f531

**Comment by WolfMad** [comment]
hi a small fix refresh the update list
/usr/lib/linuxmint/mintUpdate/mintUpdate.py
line 836 and 837

comment out the line 836
close the brackets on line 837

```
                    refresh_command.extend(["--use-synaptic",])
                                            #str(self.application.window.get_window().get_xid())])
```
rcalixte you do not need to be root to refresh the update list
