### ISSUE TITLE
Ctrl+Click doesn't open new tab in browsers

### ISSUE THREAD

**Issue by outhud** [linuxmint/wayland#47]
### Distribution

Mint

### Package version

6.0.4

### Graphics hardware in use

Intel Skylake GT2 [HD Graphics 520]

### Frequency

Always

### Bug description

Holding left Ctrl while clicking on a link opens it in a new tab in Chrome and Firefox by default.

This works in X11 sessions, but not in Wayland.

In Wayland it just opens in the link in the current tab, as if the Ctrl press isn't being seen by the browser.

Tested in both Chrome and Firefox.

### Steps to reproduce

Ctrl+Click a link in Chrome or Firefox in Wayland

### Expected behavior

Link should in new tab.

**Comment by JosephMcc** [comment]
Duplicate https://github.com/linuxmint/wayland/issues/1
