### ISSUE TITLE
Keyboard layout is English and cannot be changed

### ISSUE THREAD

**Issue by KarfiolosHus** [linuxmint/wayland#51]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

AMD RX 580

### Frequency

Always

### Bug description

Keyboard is American English, but in settings it is still says Hungarian
![Képernyőkép – 2024-01-17 21-25-49](https://github.com/linuxmint/wayland/assets/82511463/4ffe88b9-b9d7-4779-bf11-c65a89d19ab2)
Changing it and back didn!t help

### Steps to reproduce

1. Boot up Cinnamon on Wayland

### Expected behavior

- Should only use the one installed keyboard layout

**Comment by leigh123linux** [comment]
https://github.com/linuxmint/wayland/issues/14

**Comment by DAMEK86** [comment]
on my mint system (same as @KarfiolosHus), i miss the hole layout tab
x:
![image](https://github.com/linuxmint/wayland/assets/5206812/8c70b9b4-c1e8-4de4-8fde-0b5ce6d83837)
wayland:
![Screenshot from 2024-01-19 21-37-39](https://github.com/linuxmint/wayland/assets/5206812/7608ad56-6d61-4b80-b80d-183afc4daab2)
