### ISSUE TITLE
Cinnamon on Wayland Session Fails to Start

### ISSUE THREAD

**Issue by JohnDoe8771** [linuxmint/wayland#59]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

NVIDIA GeForce RTX 2070 Super

### Frequency

Always

### Bug description

When starting a Cinnamon on Wayland session from the LightDM login screen, the screen simply goes to black with a flashing cursor and does not start the Cinnamon session, necessitating the restart of LightDM from a tty console. Below are what I believe to be the relevant logs from /var/log/syslog

`Jan 28 18:42:41 removed-LM systemd[1]: Started Session c4 of User removed.`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.01362s: Could not read /home/removed/.config/autostart/redshift-gtk.desktop: Could not parse desktop file redshift-gtk.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.01556s: Could not read /home/removed/.config/autostart/megasync.desktop: Could not parse desktop file megasync.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.01569s: Could not read /home/removed/.config/autostart/kalarm.autostart.desktop: Could not parse desktop file kalarm.autostart.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.01923s: Could not read /etc/xdg/autostart/org.kde.kdeconnect.daemon.desktop: Could not parse desktop file org.kde.kdeconnect.daemon.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.01984s: Could not read /etc/xdg/autostart/gsettings-data-convert.desktop: Could not parse desktop file gsettings-data-convert.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.02045s: Could not read /etc/xdg/autostart/kalarm.autostart.desktop: Could not parse desktop file kalarm.autostart.desktop or it references a not found TryExec binary`    
`Jan 28 18:42:41 removed-LM kernel: [ 1030.471305] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership`    
`Jan 28 18:42:41 removed-LM kernel: [ 1030.536323] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: WARNING: t+0.15837s: App 'cinnamon-wayland.desktop' respawning too quickly`    
`Jan 28 18:42:41 removed-LM cinnamon-session[7152]: CRITICAL: t+0.15850s: Unable to start session: A program required by the session failed to start. App ID: 'cinnamon-wayland.desktop'. Startup ID: '107408e7524324fd83170649256159250500000071520000'.`    
`Jan 28 18:42:41 removed-LM kernel: [ 1030.786624] nvidia-prime[7322]: segfault at 18 ip 00007f223f932cf4 sp 00007ffe4ebf45c0 error 4 in libgtk-3.so.0.2404.29[7f223f82a000+383000]`    
`Jan 28 18:42:41 removed-LM kernel: [ 1030.786631] Code: c4 08 5b 5d c3 90 f3 0f 1e fa 48 8b 7f 10 48 85 ff 74 0b e9 2e c7 ff ff 66 0f 1f 44 00 00 48 83 ec 08 48 89 d7 e8 1c 2d 17 00 <48> 8b 40 18 48 8b 78 10 e8 6f 06 09 00 48 83 c4 08 48 89 c7 e9 03`    
`Jan 28 18:42:41 removed-LM systemd[1]: Started Process Core Dump (PID 7572/UID 0).`    
`Jan 28 18:42:42 removed-LM systemd[1]: Stopping Session c3 of User lightdm...`    
`Jan 28 18:42:42 removed-LM systemd[1]: session-c3.scope: Deactivated successfully.`    
`Jan 28 18:42:42 removed-LM systemd[1]: Stopped Session c3 of User lightdm.`    
`Jan 28 18:42:42 removed-LM systemd[1]: session-c3.scope: Consumed 1.063s CPU time.`    

### Steps to reproduce

Start a Cinnamon on Wayland session. Error occurs using both the 535 and 545 nVidia proprietary drivers.

### Expected behavior

Cinnamon on Wayland session starts as normal.

### Additional information

I will try a fresh and clean setup sometime in the near future when I have time to try that, will update this thread when I have done so.

**Comment by leigh123linux** [comment]
Your nvidia driver isn't working properly.

```
Jan 28 18:42:41 removed-LM kernel: [ 1030.471305] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership

Jan 28 18:42:41 removed-LM kernel: [ 1030.536323] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership
```

**Comment by JohnDoe8771** [comment]
> Your nvidia driver isn't working properly.
> 
> ```
> Jan 28 18:42:41 removed-LM kernel: [ 1030.471305] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership
> 
> Jan 28 18:42:41 removed-LM kernel: [ 1030.536323] [drm:nv_drm_master_set [nvidia_drm]] *ERROR* [nvidia-drm] [GPU ID 0x00000a00] Failed to grab modeset ownership
> ```

I tried reinstalling both the kernel and the nvidia drivers and yet the issue persists.

**Comment by JohnDoe8771** [comment]
Also, to add in the additional troubleshooting steps I tried, I disabled the nomodeset option in /etc/default/grub (enabled as part of getting tty to work properly), and when that didn't work I reinstalled grub using the boot-repair utility.

**Comment by redchieftheoriginal** [comment]
encountered the same bug. Also using Nvidia proprietary drivers, I have to power down the machine manually to restart

**Comment by Lunaisdedd** [comment]
Same bug here, latest rtx 3070 drivers x11 works perfect wayland is black/greyish until i select x11 again
