### ISSUE TITLE
mintupdate can't apply updates

### ISSUE THREAD

**Issue by carlosmintfan** [linuxmint/wayland#66]
### Distribution

Mint 21.3

### Package version

6.0.4

### Frequency

Always

### Bug description

When I press the "Apply updates" button in mintUpdate, it fails, even without asking me for a password. That's because `get_xid()` isn't available for Wayland windows.

### Steps to reproduce

1. Open mintUpdate
2. Make sure some updates are available
3. Click on "Apply Updates"
4. See that the updates aren't getting applied

### Expected behavior

The updates should be applied normally

**Comment by mtwebster** [comment]
https://github.com/linuxmint/wayland/issues/64

**Comment by carlosmintfan** [comment]
Oh, sorry :)

**Comment by carlosmintfan** [comment]
@mtwebster I have a question to this: I automatically thought this was because of `get_xid`, to connect the synaptic window to the mintUpdate window. Does this issue with get_xid exist or not?
