### ISSUE TITLE
Modifier Keys Not Detected in Applications

### ISSUE THREAD

**Issue by ConnivingKhajiit** [linuxmint/wayland#75]
### Distribution

Linux Mint 21.3 Virginia

### Package version

Cinnamon 6.0.4

### Graphics hardware in use

AMD RX 580 8G

### Frequency

Always

### Bug description

Shift, Alt, Ctrl keys do not respond to certain applications (I presume those that use hardware acceleration)
I have tested the applications shown in the reproduction steps.
Noteably, this report was written in the Wayland session, so standard typing with shift does still work, both in the game I tested (renaming a replay with a capital letter in War Thunder works, but its in-game function does not), the browser I typed this in, xed, cinnamenu, and gnome-terminal.

### Steps to reproduce

Login to cinnamon session.

Launch a game through steam (native package) (can be either proton DXVK or WineD3D (Madness: Project Nexus), native openGL (Portal), or native Vulkan (War Thunder))) or outside of steam (Besiege 64-bit).
*note that typing in the console in Portal, the shift key does function properly.
Attempt to modifiy keyboard controls to tie a function to one of these keys, or use them.
Observe that they are not registered.
OR 
Launch a standard application like Thunderbird Mail (native package) or Spotify (PPA from Software Manager).
Attempt to select multiple items (songs/emails).
Observe that ctrl/shift modifiers do not register, only a new single selection is made.
OR
run xev.
Observe that these modifiers are not detected by this command, but mouse and other keys are.

### Expected behavior

In War Thunder, shift should bring up sniper mode.
xev should output that it detects shift, alt, ctrl.
Thunderbird and spotify should select mutliple items (also applies to Nemo file manager).
Shift in Madness: Project Nexus should modify your melee, the practice mode is not possible to complete without this.
Registering new hotkeys in Portal and Besiege should work upon clicking the key, but it never leaves the "awaiting key" state.

### Additional information

I am using the amdgpu driver with an undervolt and memory overclock. It is stable.
I tested this using my keyboard in wired and bluetooth mode with the same results.
Linux kernel 5.15.0-101
Vulkan games were run with Mangohud (not installed from package manager) but opengl was not
Also, Alt-Tabbing, Ctr+Alt+Del'ing, and Ctrl+Shift+Esc (hotkey to open gnome-system-montior) functions properly so this is an application issue.
My cpu (i5-2500k) has an igpu, but it is disabled in bios.

I can provide more information, like inxi, if you wish.

**Comment by MrJinx123** [comment]
I too am having what I believe to be a related issue, I have been using the new mint release in wayland mode only and I am having issues with the shift key being recognized in WayDroid, and various vnc remote control apps like Virt-Viewer and Virtual Machine Manager's built in remote control. For the native RC apps, The issue only happen while in the remote session. Makes it very hard to enter complex passwords.

System:
  Kernel: 5.15.0-101-generic x86_64 bits: 64 compiler: gcc v: 11.4.0 Desktop: Cinnamon 6.0.4
    tk: GTK 3.24.33 wm: muffin vt: 8 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia
    base: Ubuntu 22.04 jammy
Machine:
  Type: Laptop System: Dell product: Inspiron 13-5378 v: N/A serial: <superuser required> Chassis:
    type: 9 serial: <superuser required>
  Mobo: Dell model: 0XC4P5 v: A00 serial: <superuser required> UEFI: Dell v: 1.35.0
    date: 10/18/2021
Battery:
  ID-1: BAT0 charge: 39.1 Wh (100.0%) condition: 39.1/42.0 Wh (93.1%) volts: 12.8 min: 11.4
    model: BYD DELL FW8KR14 type: Li-ion serial: <filter> status: Full
CPU:
  Info: dual core model: Intel Core i5-7200U bits: 64 type: MT MCP smt: enabled
    arch: Amber/Kaby Lake note: check rev: 9 cache: L1: 128 KiB L2: 512 KiB L3: 3 MiB
  Speed (MHz): avg: 800 min/max: 400/3100 cores: 1: 800 2: 800 3: 800 4: 800 bogomips: 21599
  Flags: avx avx2 ht lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx
Graphics:
  Device-1: Intel HD Graphics 620 vendor: Dell driver: i915 v: kernel ports: active: eDP-1
    empty: HDMI-A-1 bus-ID: 00:02.0 chip-ID: 8086:5916 class-ID: 0300
  Device-2: Realtek Integrated Webcam HD type: USB driver: uvcvideo bus-ID: 1-5:2
    chip-ID: 0bda:58c2 class-ID: 0e02 serial: <filter>
  Display: wayland server: X.org v: 1.21.1.4 with: Xwayland v: 22.1.1 driver: X:
    loaded: modesetting unloaded: fbdev,vesa gpu: i915 display-ID: 0
  Monitor-1: eDP-1 model: BOE Display res: 1920x1080 dpi: 166 size: 294x165mm (11.6x6.5")
    diag: 337mm (13.3") modes: 1920x1080
  OpenGL: renderer: Mesa Intel HD Graphics 620 (KBL GT2) v: 4.6 Mesa 23.2.1-1ubuntu3.1~22.04.2
    direct render: Yes
Audio:
  Device-1: Intel Sunrise Point-LP HD Audio vendor: Dell driver: snd_hda_intel v: kernel
    bus-ID: 00:1f.3 chip-ID: 8086:9d71 class-ID: 0403
  Sound Server-1: ALSA v: k5.15.0-101-generic running: yes
  Sound Server-2: PulseAudio v: 15.99.1 running: yes
  Sound Server-3: PipeWire v: 0.3.48 running: yes
Network:
  Device-1: Intel Wireless 3165 driver: iwlwifi v: kernel pcie: speed: 2.5 GT/s lanes: 1
    bus-ID: 01:00.0 chip-ID: 8086:3165 class-ID: 0280
  IF: wls8 state: up mac: <filter>
  IF-ID-1: lxcbr0 state: down mac: <filter>
Bluetooth:
  Device-1: Intel Bluetooth wireless interface type: USB driver: btusb v: 0.8 bus-ID: 1-6:3
    chip-ID: 8087:0a2a class-ID: e001
  Report: hciconfig ID: hci0 rfk-id: 0 state: up address: <filter> bt-v: 2.1 lmp-v: 4.2
    sub-v: 1000 hci-v: 4.2 rev: 1000
Drives:
  Local Storage: total: 238.47 GiB used: 70.35 GiB (29.5%)
  ID-1: /dev/sda vendor: Samsung model: SSD PM851 2.5 7mm 256GB size: 238.47 GiB speed: 6.0 Gb/s
    type: SSD serial: <filter> rev: 8D0Q scheme: GPT
Partition:
  ID-1: / size: 233.18 GiB used: 70.34 GiB (30.2%) fs: ext4 dev: /dev/sda2
  ID-2: /boot/efi size: 511 MiB used: 6.1 MiB (1.2%) fs: vfat dev: /dev/sda1
Swap:
  ID-1: swap-1 type: file size: 2 GiB used: 256 KiB (0.0%) priority: -2 file: /swapfile
USB:
  Hub-1: 1-0:1 info: Hi-speed hub with single TT ports: 12 rev: 2.0 speed: 480 Mb/s
    chip-ID: 1d6b:0002 class-ID: 0900
  Device-1: 1-5:2 info: Realtek Integrated Webcam HD type: Video driver: uvcvideo interfaces: 2
    rev: 2.0 speed: 480 Mb/s power: 500mA chip-ID: 0bda:58c2 class-ID: 0e02 serial: <filter>
  Device-2: 1-6:3 info: Intel Bluetooth wireless interface type: Bluetooth driver: btusb
    interfaces: 2 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 8087:0a2a class-ID: e001
  Device-3: 1-7:4 info: Elan Micro Touchscreen type: HID driver: hid-multitouch,usbhid
    interfaces: 1 rev: 2.0 speed: 12 Mb/s power: 100mA chip-ID: 04f3:2494 class-ID: 0300
  Hub-2: 2-0:1 info: Super-speed hub ports: 6 rev: 3.0 speed: 5 Gb/s chip-ID: 1d6b:0003
    class-ID: 0900
Sensors:
  System Temperatures: cpu: 44.0 C pch: 43.0 C mobo: 42.0 C sodimm: SODIMM C
  Fan Speeds (RPM): cpu: 0
Repos:
  Packages: 2695 apt: 2629 flatpak: 48 snap: 18
  No active apt repos in: /etc/apt/sources.list
  Active apt repos in: /etc/apt/sources.list.d/google-chrome.list
    1: deb [arch=amd64] https: //dl.google.com/linux/chrome/deb/ stable main
  Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list
    1: deb http: //packages.linuxmint.com virginia main upstream import backport
    2: deb http: //archive.ubuntu.com/ubuntu jammy main restricted universe multiverse
    3: deb http: //archive.ubuntu.com/ubuntu jammy-updates main restricted universe multiverse
    4: deb http: //archive.ubuntu.com/ubuntu jammy-backports main restricted universe multiverse
    5: deb http: //security.ubuntu.com/ubuntu/ jammy-security main restricted universe multiverse
  Active apt repos in: /etc/apt/sources.list.d/warpdotdev.list
    1: deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/warpdotdev.gpg] https: //releases.warp.dev/linux/deb stable main
  Active apt repos in: /etc/apt/sources.list.d/waydroid.list
    1: deb [signed-by=/usr/share/keyrings/waydroid.gpg] https: //repo.waydro.id/ jammy main
  Active apt repos in: /etc/apt/sources.list.d/winehq-jammy.sources
    1: deb [arch=amd64 i386] https: //dl.winehq.org/wine-builds/ubuntu jammy main
Info:
  Processes: 263 Uptime: 2h 57m wakeups: 1 Memory: 7.62 GiB used: 3.24 GiB (42.5%) Init: systemd
  v: 249 runlevel: 5 Compilers: gcc: 11.4.0 alt: 11/12 Client: Cinnamon v: 6.0.4 inxi: 3.3.13

**Comment by JosephMcc** [comment]
This is known: https://github.com/linuxmint/wayland/issues/1
