### ISSUE TITLE
After Wayland trial, cannot return to a working Cinnamon session

### ISSUE THREAD

**Issue by wujastyk** [linuxmint/wayland#78]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel HD graphics

### Frequency

Always

### Bug description

Cinnamon 6.0.4 tk: GTK 3.24.33, wm: muffin vt: 7 dm: LightDM 1.30.0 Distro: Linux Mint 21.3 Virginia base. Everything up to date. Thinkpad T580.

After trying Wayland (no success) I cannot get a good Cinnamon session again.

### Steps to reproduce

I tried Wayland and got a black screen. Nothing. So I switched off the laptop and then restarted. I tried to log in normally to Cinnamon, but no luck. I get the session login prompt (lightdm) and appear to have a good login. But then I arrive at a screen that shows only the Cinnamon background. No icons, no panel. The mouse moves.  There's no response to any keyboard or mouse commands.

### Expected behavior

Normal Cinnamon login

### Additional information

I have tried the fix mentioned in "Wayland Read this first" ([viewtopic.php?t=411761](https://forums.linuxmint.com/viewtopic.php?t=411761)). My system doesn't have a lightdm.conf file in /etc/lightdm. It has just a slick-greeter.conf and users.conf, and in /etc/lightdm/lightdm.confḍ there is a file 70-linuxmint.conf.
None of these files has any lines about autologin.

Any suggestions?

I [reported this at the Wayland Linux Mint forum](https://forums.linuxmint.com/viewtopic.php?t=416558), but I think this may be the more appropriate group for getting assistance.

**Comment by wujastyk** [comment]
From an alt-ctrl-F4 CLI session I have installed MATE and this gives me an alternative login option that works just fine.  At least I can now get on with work.  But I still want to reinstate Cinnamon functionality.

**Comment by wujastyk** [comment]
I have clawed my way back to a working Cinnamon session, but it's still very much a kludge.  From MATE I added `cinnamon --replace` and `nemo-desktop` to the list of Startup Applications.  Now, I can log in to Cinnamon and get a working session.  First, I see the empty unresponsive desktop; then after a second when the above commands run, the desktop is populated from `~/Desktop` and I get a panel and mouse control.  But in most respects the session has forgotten my themes, panel items, etc.   

Somehow, trying Wayland smashed my Cinnamon installation.  While I'm sort of back, it really isn't a stable, satisfactory situation.

**Comment by rcalixte** [comment]
@wujastyk Do you have system backups that you can use to restore your system? Do you have any logs that could indicate what possibly went wrong? The fact that you are getting segmentation faults while running Timeshift suggests something unfortunately is very broken either with the software or hardware on your system.

Regarding the forum post, `gsmartcontrol` is a kind of software you could use to check your disk's health. As mentioned in the forum post, `fsck` only checks your filesystem.

If you check your disk and a live USB environment works, it might be easiest to backup your files to an external hard drive and then reinstall. It sounds like that might be the shortest path to restoring your working state.

**Comment by wujastyk** [comment]
@rcalixte I *did* have a Timeshift backup from last week, but while I've been struggling with my system, that got overwritten by a new one from *after* my Wayland difficulties.  Damn, I didn't think of that.  I should have switched off Timeshift's auto-schedule as soon as I had difficulties.

By the way, there are many reports all over the web of people getting the `segmentation fault` from Timeshift.  As far as I can see, it's always when people (like me) are running it from the CLI.  When running it from a graphical interface, that particular problem doesn't seem to arise.  

I've checked the disk and partitions health with `gnome-disks` and looked at them with `gparted` (and `fsck`).  No problems.

I've just installed `gsmartcontrol` at your suggestion, but it doesn't report anything useful because my disk isn't under SMART control.

I take what you say about backup-reinstall, and maybe that's what I'll do.  But I am dogged by the suspicion that this is something very very simple.  Just a wrong comma in a conf file or something like that.

I'd like to ask, generally, what actually happens when you log into Linux Mint using the Wayland option?  What files and setting get changed?  Is that documented anywhere?  It looks to me as if the attempt to use Wayland, followed by a system reset, changed a critical setting that has crippled Cinnamon.

**Comment by wujastyk** [comment]
I'm afraid I cannot give more time to trying to solve this post-Wayland problem with Cinnamon.  So I am currently backing up, wiping my disk, and reinstalling LM+Cinnamon.  

A big thank you to everyone who gave thought to this problem.  I'm really grateful - as always - to the Git and Linux community.

Best wishes,
Dominik

**Comment by rcalixte** [comment]
> By the way, there are many reports all over the web of people getting the `segmentation fault` from Timeshift. As far as I can see, it's always when people (like me) are running it from the CLI. When running it from a graphical interface, that particular problem doesn't seem to arise.

This sounds like it might be a common issue and there should be an Issue open at [the repository for Timeshift](https://github.com/linuxmint/timeshift/issues) with the stack trace, assuming something doesn't already exist for this.




> I take what you say about backup-reinstall, and maybe that's what I'll do. But I am dogged by the suspicion that this is something very very simple. Just a wrong comma in a conf file or something like that.

It would have to come down to you knowing what changed. This is a first type of this issue since the experimental Wayland session was made available for testing.



> I'd like to ask, generally, what actually happens when you log into Linux Mint using the Wayland option? What files and setting get changed? Is that documented anywhere? It looks to me as if the attempt to use Wayland, followed by a system reset, changed a critical setting that has crippled Cinnamon.

There isn't anything strenuous here as far as I understand. Again, this is the first issue of this kind that I am aware of so I am inclined to believe that it's an isolated incident for now.



> I'm afraid I cannot give more time to trying to solve this post-Wayland problem with Cinnamon. So I am currently backing up, wiping my disk, and reinstalling LM+Cinnamon.

If you have the storage space for additional backups going further back, I would encourage that so that hopefully you don't end up in this situation again.
