### ISSUE TITLE
Update Manager has permissions problems - won't refresh or update non-root user

### ISSUE THREAD

**Issue by TomBoland1** [linuxmint/wayland#90]
### Distribution

Mint 21.3

### Package version

6.0.4

### Graphics hardware in use

Intel AlderLake-S GT1

### Frequency

Always

### Bug description

Refresh button returns "Could not refresh the list of updates". 
Log file shows "Exception occurred in the refresh thread: <class 'AttributeError'>"
Update button greyed out.

### Steps to reproduce

Method 1 - System Tray or Menu - FAIL
- Launch Update Manager from System tray or menu.
- Click on Refresh Updates.
- Refresh fails as described.

Method 2 -Command Line Current User - FAIL
- Launch Terminal  of choice
- _mintUpdate_
- Click on Refresh Updates.
- Refresh fails as described.

Method 3 -Command Line _sudo_ - SUCCESS
- Launch Terminal  of choice
- _sudo mintUpdate_
- Click on Refresh Updates.
- Refreshes as expected.

### Expected behavior

For Update Manager to work as intended.

### Additional information

mintUpdate window does not resize from button upper right, minimize and maximize do function as intended.
nemo Open as Root fails.

Permission files for reference
/etc/sudoers.d/mintupdate:
```
# Allow any user to check for new system updates without
# requiring user authentication.

ALL ALL = NOPASSWD:/usr/bin/mint-refresh-cache
ALL ALL = NOPASSWD:/usr/lib/linuxmint/mintUpdate/synaptic-workaround.py
ALL ALL = NOPASSWD:/usr/lib/linuxmint/mintUpdate/dpkg_lock_check.sh
```
/etc/polkit-1/localauthority/50-local.d/52-tom.pkla
```
[tom is allowed to modify stuff]

[Install or Remove Software]
Identity=unix-user:tom
Action=org.freedesktop.packagekit.*
ResultInactive=no
ResultActive=yes
Identity=unix-user:tom
Action=org.debian.apt.install-or-remove-packages
ResultInactive=no
ResultActive=yes
Identity=unix-user:tom
Action=org.freedesktop.packagekit.package-remove
ResultInactive=no
ResultActive=yes


[Update Manger]
Identity=unix-user:tom
Action=com.ubuntu.pkexec.synaptic
ResultInactive=no
ResultActive=yes

[Firewall]
Identity=unix-user:tom
Action=com.ubuntu.pkexec.gufw
ResultInactive=no
ResultActive=yes

[Timeshift]
Identity=unix-user:tom
Action=in.teejeetech.pkexec.timeshift-gtk
ResultInactive=no
ResultActive=yes

[gparted]
Identity=unix-user:tom
Action=org.gnome.gparted
ResultInactive=no
ResultActive=yes

[Software Sources]
Identity=unix-user:tom
Action=com.linuxmint.mintsources
ResultInactive=no
ResultActive=yes
```

**Comment by haggen88** [comment]
perhaps it is related to #26 , #22

**Comment by mtwebster** [comment]
Yes, this is fixed in Cinnamon:
https://github.com/linuxmint/cinnamon/commit/529d1412f116a5e382d6fa424d3aec3fd13a9299
